language: java
sudo: required
before_install:
  - chmod +x mvnw

script:
  - ./mvnw clean install -B

services:
  - docker

deploy:
- provider: heroku
  app: unique-app-name-ci
  api_key:
    secure: 5cW4PFC1511mSd6KZBwtHx4jFLxGK6t0rvZdUFX61IfgkhWZAxiV6diOw3QzzgXb4BH7y8YvmLWNIE8QstjYKgka/xJex6OBUBIR+z2b2b3QHDTmXVpS865NIuTfp0u2bqzlzq1ZW2destPzYYYPuoHrbBHvNDOoqg+461VEUfMxQ8fL/+0RWybpjqFTP2OWot/CRmmSWzElyEw2I9M3CH2UMRlhwUxnZmIx8UKAVqC1b2yFWLs/uScrzeQAeifbz7meT8iQog48Y9DuurogUCf9W8hc5Xs/Y43uGl5Qs6cV2PRoFVvsmRNtb/CsTh50DpursTpWWGHhFYbd4DAgA1qYg9YcnaLkyYSrzzFIQPLAVma6ed80/mxGvq4QZBq64eYgf3jRqnyADEOJ70usXcpgbXZCAx/0GGH/BMbD4roMSBXupdVn59EMVA2aeJ5nvpAN5wZCn2IlwzToTF5l1/PQGPwgv/aPAMY+rQVuWIqm/4oktbvjJNv9//WIWvoakYDQ29mFLL2pSZqqDNkMGavM9HV0WBk9noG+gNuUeFryqRQKyqWGAzEI+yG48tkTccAbosLLLAbpYI+HP836uKePFz8NRoHzkn/vrdswMuxvdhv0h0dKeInc4hF+X5ECm9qyCo1ov9DifyIjCl34Qs5U8vY+xBxM/kza2aWWhGw=
- provider: script
  script: bash docker_push.sh
  on:
    branch: master

env:
  global:
  - secure: UeGzZ1in2MYG+WsgMNooaMwhKyOtapCuQXDZn27ighNIQYlBv3mgSXYa47OU2ZZO//gr4pLjcg1f4TyFHiqVruJ1TIeYSjLSC9n4TFUf88BOUzqi/w9Oqb78g6vVWP5mAd4oMy0hvevxHbauMrTw//nVqrnvvCZLpqQG7W8bVBHXQ2Av7P+i9c4Q+fpCZ9gMt9+VEkaBrq3/6poz5XgTmv6SHF6VIJSbi9kBCGwfl9yDSDsekpWXVU+E/2lpUr9iG+3PAgpJnOo6VBFuL+wRHnqqaWGQQbGa8JpRJBsclA0VQiZ37XlbEXGswjxDSj0J0+0tzXYgqSkpUXr2dgzFz6h+8BA1A7wB//lOY56HOF96SFtPvFVMFxcz08AlsD2zpi9T0iBoEAAvyJGAOaRoyv3LoTi5yhbnRwseIQcIE3c2qcTi4LWaC69t6zes+F0LlKpLbTgb4sY1RmPsxMnGfr6lpy885oaro/tMixfgU0I4H3vyc1VuU3z3dUJr6oUDdyt2RC7T6R4EAb9/X6nSOzwXw+2R2iTMK2OTfjBSPNSKPr3OLrrVZSuzz9aTdvt52e85DXiqR5GxkrEyciz7BADZFvYYX7MPQe/CykkNtJReyQWsiGZTgzvCH7FsUE9wkd9t0u0JBR7raEATLH/P7PJzp44VZ54reJGwexWgIck=
  - secure: m17AeWo/4GowB322yEsIsz+MABymLPawm2U57C37+srRIDhSF1GBzmzjgolfOWF35hOrUEVp2lqFq4ENagUszAKmCUz0byyQ9h+LELbU/WHb7UWEDh9oLzCBEmf29iebs80jLzhzToKlvy1O1cvknvVwyKUQ4DYaXBDKMoLp4t/lR00ejuABvfnAhX7mPkaDt76akik6K1MYbYGD/N+lSVpbJAwacaBY6kazSJlKxlZqxN3WN5I+WaY13D3rEjvB6WN0Hx3KwWO7kMGHzKzuKz9cMWlambNa8/rOOJFgBqBdvEEyVRVcAzvZqtKLx1AoxB638w/Sexo6p+9TtDtB1DvXeM2U9GBEJkLn+PKWbnLOO04dna+S5mcIO0ZF5OeMxMXmBaKrCeE+tlB79PhwOjr3gP94z//8A/IzSy7Vu3GChUHwuNdpymrNIlm8V/sXRT+YNFtRGHG6PxPJXdpahT1ZjybCj+lH46mJFmwP+ICvVajmOGosDv8Q+wzT58qmToQraMMfKnAW9Dd9S+7Aii/fEIrJyoF6QFFoYjGngFVDbA5bc1rLP87XP4xrkDiPcBkFPQCoRbvvEVbh626JyW7QExd2Sq8GsKOMExZ2OCF3at8M3xaZb6/PZvcxwDiJMvWJy2jRfu0224UQ5oubEbVwS+TyaHRC4VG9RkcTwmo=
